name: startup_try_2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

smooth_star_rating: ^1.1.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  simple_animations: ^4.1.0
  http: ^0.13.4
  fluttertoast:
  smooth_star_rating: ^1.1.1
  url_launcher: ^6.1.2
  firebase_core:
  google_sign_in: ^5.3.3
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  auto_size_text: ^3.0.0
  introduction_screen: ^3.0.2
  modal_progress_hud: ^0.1.3
  mailer: ^5.1.1
  geolocator:
  firebase_auth: ^3.3.19

dev_dependencies:
  flutter_native_splash:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1B0250"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/errorpages/
    - assets/images/introScreen/
    - assets/images/initialScreens/
    - assets/images/shopAndDeliveryUI/
    - delivery.gif

